### ISSUE TITLE
Требования от дизайнера (Кузькин)

### ISSUE THREAD

**Issue by lulu2kan** [lulu2kan/DeusVult#2]
Написать требования к задачам, авторизации и регистрации с точки зрения дизайнера: подробное описание, какие используются UI
- [x] Вход
- [x] Регистрация
- [x] Главная страница без задач
- [x] Главная страница с заполненными задачами
- [x] Добавление папки
- [x] Добавление задачи
- [x] Профиль

**Comment by Qoer** [comment]
https://github.com/lulu2kan/DeusVult/wiki/%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86-(%D0%9A%D1%83%D0%B7%D1%8C%D0%BA%D0%B8%D0%BD)
